"""add group_id column

Revision ID: 15aeca8b82bd
Revises: 0f2d7112eb33
Create Date: 2025-09-30 15:36:28.984248

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '15aeca8b82bd'
down_revision: Union[str, Sequence[str], None] = '0f2d7112eb33'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('group_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'group_id')
    # ### end Alembic commands ###
