"""add faculty and semester columns

Revision ID: 8c6f5503287a
Revises: ecc7e689fb80
Create Date: 2025-10-06 20:56:06.674528

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8c6f5503287a'
down_revision: Union[str, Sequence[str], None] = 'ecc7e689fb80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('groups', sa.Column('faculty', sa.String(), nullable=False))
    op.add_column('groups', sa.Column('semester', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('groups', 'semester')
    op.drop_column('groups', 'faculty')
    # ### end Alembic commands ###
